# Generated by Django 4.1.3 on 2022-11-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="date_posted",
        ),
    ]
